version: '3.4'

services:
  php:
    build:
      context: .
      target: sylius_minimum_order_value_plugin_php
      network: host
    image: nedac/sylius_minimum_order_value_plugin_php:latest
    environment:
      - APP_ENV=test
      - DATABASE_URL=mysql://sylius:minimum_order_value@127.0.0.1:3306/sylius_minimum_order_value
    volumes:
      - .:/srv/sylius
    network_mode: host

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sylius_minimum_order_value
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=minimum_order_value
    network_mode: host

  nginx:
    build:
      context: .
      target: sylius_minimum_order_value_plugin_nginx
    image: nedac/sylius_minimum_order_value_plugin_nginx:latest
    volumes:
      - .:/srv/sylius
    network_mode: host

  nodejs:
    build:
      context: .
      target: sylius_minimum_order_value_plugin_nodejs
    image: nedac/sylius_minimum_order_value_plugin_nodejs:latest
    volumes:
      - .:/srv/sylius
    network_mode: host

  chrome:
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    network_mode: host
