version: '3.4'

services:
  php:
    build:
      context: .
      target: sylius_minimum_order_value_plugin_php
      network: host
    image: ghcr.io/nedac-sorbo/sylius_minimum_order_value_plugin_php:latest
    environment:
      - APP_ENV=test
      - DATABASE_URL=mysql://sylius:minimum_order_value@127.0.0.1:3306/sylius_minimum_order_value
    volumes:
      - .:/srv/sylius/vendor/nedac/sylius-minimum-order-value-plugin
      - ./etc/build:/srv/sylius/etc/build
      - public-media:/srv/sylius/public/media:rw
      - public:/srv/sylius/public:rw
    network_mode: host

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sylius_minimum_order_value
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=minimum_order_value
    network_mode: host

  nginx:
    build:
      context: .
      target: sylius_minimum_order_value_plugin_nginx
      network: host
    image: ghcr.io/nedac-sorbo/sylius_minimum_order_value_plugin_nginx:latest
    volumes:
      - public:/srv/sylius/public:ro
      - public-media:/srv/sylius/public/media:ro,nocopy
    network_mode: host

  nodejs:
    build:
      context: .
      target: sylius_minimum_order_value_plugin_nodejs
      network: host
    image: ghcr.io/nedac-sorbo/sylius_minimum_order_value_plugin_nodejs:latest
    volumes:
      - .:/srv/sylius/vendor/nedac/sylius-minimum-order-value-plugin
    network_mode: host

  chrome:
    build:
      context: .
      target: sylius_minimum_order_value_plugin_chrome
      network: host
    image: ghcr.io/nedac-sorbo/sylius_minimum_order_value_plugin_chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    network_mode: host

volumes:
  public:
  public-media:
