name: default

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose up -d --build
# FIXME: Check the php service state
#      - name: Wait for services
#        run: |
#            while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q php)")"; do
#              echo "$status";
#              case $status in
#                starting) sleep 1;;
#                healthy) exit 0;;
#                unhealthy)
#                  docker-compose ps
#                  docker-compose logs
#                  exit 1
#                ;;
#              esac
#            done
#            exit 1
      - name: Install sub dependencies
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-minimum-order-value-plugin && composer install)"
      - name: Code style
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-minimum-order-value-plugin && vendor/bin/phpcs)"
      - name: Static analysis
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-minimum-order-value-plugin && vendor/bin/phpstan analyse src/ tests/ --level max)"
      - name: Unit tests
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-minimum-order-value-plugin && vendor/bin/phpunit --testdox)"
      - name: Create database schema
        run: docker-compose exec -T php bin/console doctrine:schema:create
      - name: End to end tests
        run: docker-compose exec -T php vendor/bin/behat
